FYP/Controllers/PaperCreationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FYP.Models;

namespace FYP.Controllers
{
    public class PaperCreationController : Controller
    {
        //
        // GET: /PaperCreation/
        FYP_DB_Entities obj = new FYP_DB_Entities();
        List<int> randomNumber = new List<int>();
        List<Question> question_mcq = new List<Question>();
        List<Question> question_tf = new List<Question>();
        Random rand = new Random();

        #region Check Exam Status
        public ActionResult Exam_Status(string Success_Message)
        {
            if (Session["User_Id"] != null && Session["User_Password"] != null)
            {
                List<Subject> Subjects = new List<Subject>();
                var user = (string)Session["User_Id"];
                User u = obj.Users.First(a => a.User_Id == user);
                List<Subject> subjects = u.Subjects.ToList();
                foreach(var subject in subjects)
                {
                    bool exam = obj.Exams.Any(a => a.Subject_Id == subject.Subject_Id && (a.Status == "MidExam" || a.Status == "FinalExam"));
                    if(exam)
                    {
                        Subjects.Add(subject);
                    }
                }
                //ViewBag.total_subjects = subjects;
                ViewBag.Success_Message = Success_Message;
                return View(Subjects);
            }
            else
            {
                return RedirectToAction("LoginPage", "Login");
            }
        }
        #endregion
        #region Set Criteria For Paper
        public ActionResult Create_Criteria(string Subject_Id, string Error_Message)
        {
            if (Session["User_Id"] != null && Session["User_Password"] != null)
            {
                Subject subject = obj.Subjects.First(a => a.Subject_Id == Subject_Id);
                Exam exam = obj.Exams.First(a => a.Subject_Id == Subject_Id);

                // pick easy , medium and difficult questions for MCQ's and True/False
                var easymcq = subject.Questions.Where(a => a.Type.Equals("MCQ-E"));
                var mediummcq = subject.Questions.Where(a => a.Type.Equals("MCQ-M"));
                var difficultmcq = subject.Questions.Where(a => a.Type.Equals("MCQ-D"));
                var easytf = subject.Questions.Where(a => a.Type.Equals("True/False-E"));
                var mediumtf = subject.Questions.Where(a => a.Type.Equals("True/False-M"));
                var difficulttf = subject.Questions.Where(a => a.Type.Equals("True/False-D"));
                var totalmcq = subject.Questions.Where(a => a.Type.Equals("MCQ-E") || a.Type.Equals("MCQ-M") || a.Type.Equals("MCQ-D"));
                var totaltf = subject.Questions.Where(a => a.Type.Equals("True/False-E") || a.Type.Equals("True/False-M") || a.Type.Equals("True/False-D"));

                int easymcq_count = easymcq.Count();
                int mediummcq_count = mediummcq.Count();
                int difficultmcq_count = difficultmcq.Count();
                int easytf_count = easytf.Count();
                int mediumtf_count = mediumtf.Count();
                int difficulttf_count = difficulttf.Count();
                int totalmcq_count = totalmcq.Count();
                int totaltf_count = totaltf.Count();

                ViewBag.easymcq = easymcq_count;
                ViewBag.mediummcq = mediummcq_count;
                ViewBag.difficultmcq = difficultmcq_count;
                ViewBag.easytf = easytf_count;
                ViewBag.mediumtf = mediumtf_count;
                ViewBag.difficulttf = difficulttf_count;
                ViewBag.totalmcq = totalmcq_count;
                ViewBag.totaltf = totaltf_count;


                // Calculate percentage for each easy , medium and difficult MCQ's and True/False Questions
                if (totalmcq_count > 0 && totaltf_count > 0)
                {
                    float easymcqpercentage = ((easymcq_count * 100) / totalmcq_count);
                    float mediummcqpercentage = ((mediummcq_count * 100) / totalmcq_count);
                    float difficultmcqpercentage = ((difficultmcq_count * 100) / totalmcq_count);
                    float easytfpercentage = ((easytf_count * 100) / totaltf_count);
                    float mediumtfpercentage = ((mediumtf_count * 100) / totaltf_count);
                    float difficulttfpercentage = ((difficulttf_count * 100) / totaltf_count);

                    ViewBag.easymcqpercentage = easymcqpercentage;
                    ViewBag.mediummcqpercentage = mediummcqpercentage;
                    ViewBag.difficultmcqpercentage = difficultmcqpercentage;
                    ViewBag.easytfpercentage = easytfpercentage;
                    ViewBag.mediumtfpercentage = mediumtfpercentage;
                    ViewBag.difficulttfpercentage = difficulttfpercentage;
                }
                else
                {
                    ViewBag.easymcqpercentage = 0;
                    ViewBag.mediummcqpercentage = 0;
                    ViewBag.difficultmcqpercentage = 0;
                    ViewBag.easytfpercentage = 0;
                    ViewBag.mediumtfpercentage = 0;
                    ViewBag.difficulttfpercentage = 0;
                }

                ViewBag.subject = subject.Subject_Name;
                ViewBag.subject_id = subject.Subject_Id;
                ViewBag.Error_Message = Error_Message;
                ViewBag.Marks = exam.Total_Marks;
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        #endregion
        #region Create Paper For Specific Exam
        public ActionResult Create_Paper(FormCollection fc)
        {
            if (Session["User_Id"] != null && Session["User_Password"] != null)
            {
                int Subject_Id = int.Parse(fc["subject_id"]);
                string subject_name = fc["subject"];
                int total = int.Parse(fc["totalmarks"]);
                float mcq = int.Parse(fc["mcqs"]);
                float truefalse = int.Parse(fc["truefalse"]);
                int mcqmark = int.Parse(fc["mcqmark"]);
                float truefalsemark = int.Parse(fc["truefalsemark"]);
                float TotalMcq = (mcq / 100) * total;
                float Totaltruefalse = (truefalse / 100) * total;
                float mcqQuestion1 = (TotalMcq / mcqmark);
                float truefalseQuestion1 = (Totaltruefalse / truefalsemark);
                ViewBag.eachmcqmark = mcqmark;
                ViewBag.eachtfmark = truefalsemark;

                int mcqQuestions = (int)Math.Round(mcqQuestion1, MidpointRounding.AwayFromZero);
                int truefalseQuestions = total - ((mcqQuestions) * mcqmark);

                var user1 = (string)Session["User_Id"];
                User user = obj.Users.First(a => a.User_Id == user1);
                Subject subject = obj.Subjects.First(a => a.Subject_Name == subject_name && a.User_Id == user.User_Id);

                var queryforallmcq = subject.Questions.Where(a => a.Type == "MCQ-E" || a.Type == "MCQ-M" || a.Type == "MCQ-D");
                var queryforeasymcq = subject.Questions.Where(a => a.Type == "MCQ-E");
                var queryformediummcq = subject.Questions.Where(a => a.Type == "MCQ-M");
                var queryfordifficultmcq = subject.Questions.Where(a => a.Type == "MCQ-D");

                var queryforalltf = subject.Questions.Where(a => a.Type == "True/False-E" || a.Type == "True/False-M" || a.Type == "True/False-D");
                var queryforeasytf = subject.Questions.Where(a => a.Type == "True/False-E");
                var queryformediumtf = subject.Questions.Where(a => a.Type == "True/False-M");
                var queryfordifficulttf = subject.Questions.Where(a => a.Type == "True/False-D");

                int easymcq_count = queryforeasymcq.Count();
                int mediummcq_count = queryformediummcq.Count();
                int difficultmcq_count = queryfordifficultmcq.Count();
                int easytf_count = queryforeasytf.Count();
                int mediumtf_count = queryformediumtf.Count();
                int difficulttf_count = queryfordifficulttf.Count();
                int allmcq_count = queryforallmcq.Count();
                int alltf_count = queryforalltf.Count();

                if (fc["mcqe"] != null && fc["tfe"] == null)
                {
                    float mcqeasy = int.Parse(fc["mcqe"]);
                    float mcqmedium = int.Parse(fc["mcqm"]);
                    float mcqdifficult = int.Parse(fc["mcqd"]);

                    var easymcq_Questions = (mcqeasy / 100) * mcqQuestions;
                    var mediummcq_Questions = (mcqmedium / 100) * mcqQuestions;
                    var difficultmcq_Questions = (mcqdifficult / 100) * mcqQuestions;

                    if (((easymcq_Questions + 1) <= easymcq_count) && ((mediummcq_Questions + 1) <= mediummcq_count) && ((difficultmcq_Questions + 1) <= difficultmcq_count) && (truefalseQuestions <= alltf_count))
                    {
                        float a = easymcq_Questions % 1;
                        float b = mediummcq_Questions % 1;
                        float c = difficultmcq_Questions % 1;
                        float d = a + b + c;
                        if (d == 0.0)
                        {
                            if (easymcq_Questions == 0)
                            {
                                randomNumber.Clear();
                                for (int i = 0; i < Math.Floor(mediummcq_Questions); i++)
                                {
                                    int number;
                                    do
                                    {
                                        number = rand.Next(1, mediummcq_count + 1);

FYP/Views/PaperCreation/Create_Paper.cshtml
@{
    ViewBag.Title = "Create Paper";
    Layout = "~/Views/Shared/Teacher_Master_Page.cshtml";
}

<body>
    <div class="container" style="border: none; padding: 0px; border-radius: 4px;">
        <h3><b>Create Paper</b></h3>
        <hr>
        <div class="container scroll" style="border: 1px solid silver; padding: 0px; border-radius: 4px;">
            <div class="container-fluid" style="background-color: #F4F4F4; padding: 12px; border-radius: 4px;"><span class="glyphicon glyphicon-list"></span>Selected Questions</div>
            <div class="container">

                @using (Html.BeginForm("Send_Paper", "PaperCreation"))
                {
                    int count = 1;
                    <br>
                    <table class="table table-striped table-bordered">
                        <tr>
                            <th style="width:20px;"></th>
                            <th style="width:950px;"><label>Question's List</label></th>
                            <th style="text-align: center;"><label>Type</label></th>
                        </tr>

                        @foreach (var mcq in @ViewBag.MCQ)
                        {
                            <tr>
                                <td>
                                    <input type="text" value="@ViewBag.Subject_Id" name="Subject_Id" hidden />
                                    <label>@count .</label>
                                    <input type="text" name="question_@count" value="@mcq.Question_Id" hidden />
                                    <input type="text" name="mark_@count" value="@ViewBag.eachmcqmark" hidden />

                                </td>
                                <td style="height: 30px; min-width: 950px; max-width:950px; overflow:hidden; text-overflow:ellipsis; font-size: 15px;">
                                    @mcq.Questions
                                </td>
                                <td style="text-align:center;">@mcq.Type</td>
                            </tr>
                            count++;
                        }
                        @foreach (var tf in @ViewBag.TrueFalse)
                        {
                            <tr>
                                <td>
                                    <label>@count .</label>
                                    <input type="text" name="question_@count" value="@tf.Question_Id" hidden />
                                    <input type="text" name="mark_@count" value="@ViewBag.eachtfmark" hidden />

                                </td>
                                <td style="height: 30px; min-width: 950px; max-width:950px; overflow:hidden; text-overflow:ellipsis; font-size: 15px;">
                                    @tf.Questions
                                </td>
                                <td style="text-align:center;">@tf.Type</td>
                            </tr>
                            count++;
                        }
                    </table>
                    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Create_Criteria", "PaperCreation" , new { Subject_Id = ViewBag.Subject_Id })'"><span class="glyphicon glyphicon-backward"></span> Cancel</button>
                    <input type="submit" class="btn btn-success" />
                }

            </div>
            <br>
            <br>
        </div>
    </div>
</body>

FYP/Views/PaperCreation/Exam_Status.cshtml
@{
    ViewBag.Title = "Exam_Status";
    Layout = "~/Views/Shared/Teacher_Master_Page.cshtml";
}

<div class="container" style="border: none; padding: 0px; border-radius: 4px;">
    <h3><b>Create Paper</b></h3>
    <hr>
    @if (ViewBag.Success_Message != null)
    {
        <div class="alert alert-danger alert-dismissable fade in" style="text-align:center;">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            @ViewBag.Success_Message
        </div>
    }

    <div class="container" style="border: 1px solid silver; padding: 0px; border-radius: 4px;">
        <div class="container-fluid" style="background-color: #F4F4F4; padding: 12px; border-radius: 4px;"><span class="glyphicon glyphicon-edit"></span>Create Exam</div>
        <br>
        <div class="container" id="div1">
            <table class="table table-bordered" style="table-layout:fixed">
                <tr>
                    <th style="text-align:center;"><b>Subjects</b></th>
                    <th style="text-align:center;"><b>Action</b></th>
                </tr>
                @foreach (var s in Model)
                {
                    <tr>
                        <td style="text-align:center;"><div>@s.Subject_Name</div></td>
                        <td style="text-align:center;">
                            <div><button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Create_Criteria", "PaperCreation", new { Subject_Id = @s.Subject_Id})'"><span class="glyphicon glyphicon-edit"></span>Create Paper</button></div>
                        </td>
                    </tr>
                }
            </table>
        </div>

    </div>
</div>

FYP/Views/PaperCreation/Send_Paper.cshtml
@{
    ViewBag.Title = "Send_Paper";
    Layout = "~/Views/Shared/Teacher_Master_Page.cshtml";
}

<h2>Send_Paper</h2>